config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("contracts/", include('contracts.urls', namespace='contracts')),
    path("users/", include('users.urls', namespace='users')),
    path("books/", include('books.urls', namespace='books')),
    path("customers/", include('customers.urls', namespace='customers')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from homes import views as home_views

app_name = "core"

urlpatterns = [
    path("", home_views.homes, name='home'),
]

customers/urls.py
from django.urls import path
from . import views

app_name = "customers"

urlpatterns = [
    path("houselease/", views.HouseLeaseCustomerList.as_view(), name="house-lease-customer-list"),
    path("houselease/<int:pk>/", views.HouseLeaseCustomerDeatil.as_view(), name="house-lease-customer-detail"),
    path("houselease/creating/", views.HouseLeaseCustomerCreating.as_view(), name="house-lease-customer-creating"),
    path("houselease/<int:pk>/update/", views.HouseLeaseCustomerUpdate.as_view, name="house-lease-customer-update"),
    path("houselease/search/", views.houselease_customer_search, name="house-lease-customer-search"),
    path("houselease/<int:pk>/delete/", views.houselease_customer_delete, name="house-lease-customer-delete"),
    path("shoplease/", views.ShopLeaseCustomerList.as_view(), name="shop-lease-customer-list"),
    path("shoplease/<int:pk>/", views.ShopLeaseCustomerDeatil.as_view(), name="shop-lease-customer-detail"),
    path("shoplease/creating/", views.ShopLeaseCustomerCreating.as_view(), name="shop-lease-customer-creating"),
    path("shoplease/<int:pk>/update/", views.ShopLeaseCustomerUpdate.as_view, name="shop-lease-customer-update"),
    path("shoplease/search/", views.shoplease_customer_search, name="shop-lease-customer-search"),
    path("shoplease/<int:pk>/delete/", views.shoplease_customer_delete, name="shop-lease-customer-delete"),
    path("housedealing/", views.HouseDealingCustomerList.as_view(), name="house-dealing-customer-list"),
    path("housedealing/<int:pk>/", views.HouseDealingCustomerDeatil.as_view(), name="house-dealing-customer-detail"),
    path("housedealing/creating/", views.HouseDealingCustomerCreating.as_view(), name="house-dealing-customer-creating"),
    path("housedealing/<int:pk>/update/", views.HouseDealingCustomerUpdate.as_view, name="house-dealing-customer-update"),
    path("housedealing/search/", views.housedealing_customer_search, name="house-dealing-customer-search"),
    path("housedealing/<int:pk>/delete/", views.housedealing_customer_delete, name="house-dealing-customer-delete"),
    path("buildingdealing/", views.BuildingDealingCustomerList.as_view(), name="building-dealing-customer-list"),
    path("buildingdealing/<int:pk>/", views.BuildingDealingCustomerDeatil.as_view(), name="building-dealing-customer-detail"),
    path("buildingdealing/creating/", views.BuildingDealingCustomerCreating.as_view(), name="building-dealing-customer-creating"),
    path("buildingdealing/<int:pk>/update/", views.BuildingDealingCustomerUpdate.as_view, name="building-dealing-customer-update"),
    path("buildingdealing/search/", views.buildingdealing_customer_search, name="building-dealing-customer-search"),
    path("buildingdealing/<int:pk>/delete/", views.buildingdealing_customer_delete, name="building-dealing-customer-delete"),
]

customers/models.py
from django.db import models

"""below customer"""


class HouseLeaseCustomer(models.Model):

    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=30)
    updated = models.DateField(auto_now=True)
    deposit = models.IntegerField(default=0)
    month_fee = models.IntegerField(default=0)
    room = models.IntegerField(default=0)
    area_m2 = models.IntegerField(default=0)
    parking = models.BooleanField(default=False)
    elevator = models.BooleanField(default=False)
    loan = models.BooleanField(default=False)
    not_finished = models.BooleanField(default=True)
    finished = models.BooleanField()
    description = models.TextField()


class ShopLeaseCustomer(models.Model):

    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=30)
    updated = models.DateField(auto_now=True)
    deposit = models.IntegerField(default=0)
    month_fee = models.IntegerField(default=0)
    area_m2 = models.IntegerField(default=0)
    parking = models.BooleanField(default=False)
    elevator = models.BooleanField(default=False)
    not_finished = models.BooleanField(default=True)
    finished = models.BooleanField()
    description = models.TextField()


class HouseDealingCustomer(models.Model):

    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=30)
    updated = models.DateField(auto_now=True)
    price = models.IntegerField(default=0)
    room = models.IntegerField(default=0)
    area_m2 = models.IntegerField(default=0)
    parking = models.BooleanField()
    elevator = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    finished = models.BooleanField()
    description = models.TextField()


class BuildingDealingCustomer(models.Model):

    realtor = models.ForeignKey(
        "users.User", null=True, on_delete=models.CASCADE)
    guest_phone = models.CharField(max_length=30)
    updated = models.DateField(auto_now=True)
    price = models.IntegerField(default=0)
    elevator = models.BooleanField()
    not_finished = models.BooleanField(default=True)
    finished = models.BooleanField()
    description = models.TextField()

customers/forms.py
from django import forms
from . import models


class HouseLeaseCustomerForm(forms.ModelForm):
    class Meta:
        model = models.HouseLeaseCustomer
        fields = (
            "guest_phone",
            "deposit",
            "month_fee",
            "room",
            "area_m2",
            "description",
            "not_finished",
            "finished",
        )


class HouseDealingCustomerForm(forms.ModelForm):
    class Meta:
        model = models.HouseDealingCustomer
        fields = (
            "guest_phone",
            "price",
            "room",
            "area_m2",
            "parking",
            "elevator",
            "description",
            "not_finished",
            "finished",
        )


class ShopLeaseCustomerForm(forms.ModelForm):
    class Meta:
        model = models.ShopLeaseCustomer
        fields = (
            "guest_phone",
            "deposit",
            "month_fee",
            "area_m2",
            "description",
            "not_finished",
            "finished",
        )


class BuildingDealingCustomerForm(forms.ModelForm):
    class Meta:
        model = models.BuildingDealingCustomer
        fields = (
            "guest_phone",
            "price",
            "description",
            "elevator",
            "not_finished",
            "finished",
        )

customers/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from . import models, forms


class HouseLeaseCustomerList(ListView):
    model = models.HouseLeaseCustomer
    context_object_name = 'houselease_customers'
    template_name = 'customers/houselease/houselease_list.html'


class HouseLeaseCustomerDeatil(DetailView):
    model = models.HouseLeaseCustomer
    template_name = 'customers/houselease/houselease_detail.html'


class HouseLeaseCustomerCreating(CreateView):
    form_class = forms.HouseLeaseCustomerForm
    template_name = 'customers/houselease/houselease_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:house-lease-customer-list"))


class HouseLeaseCustomerUpdate(UpdateView):
    model = models.HouseLeaseCustomer
    template_name = "customers/houselease/houselease_update.html"
    fields = (
        "guest_phone",
        "deposit",
        "month_fee",
        "room",
        "area_m2",
        "description",
        "not_finished",
        "finished",
    )

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:house-lease-customer-list"))


def houselease_customer_search(request):

    deposit = int(request.GET.get("deposit", 0))
    month_fee = int(request.GET.get("month_fee", 0))
    room = request.GET.get("room", 0)
    area_m2 = int(request.GET.get("area_m2", 0))
    parking = request.GET.get("parking")
    elevator = request.GET.get("elevator")
    loan = request.GET.get("loan")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
   
    filter_args = {}
    filter_args["deposit__lte"] = deposit
    filter_args["month_fee__lte"] = month_fee
    filter_args["area_m2__gte"] = area_m2
    filter_args["room__contains"] = room
    if parking == "on":
        filter_args["parking"] = True
    if elevator == "on":
        filter_args["elevator"] = True
    if loan == "on":
        filter_args["loan"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    houselease_customers = models.HouseLeaseCustomer.objects.filter(**filter_args)
    return render(request, "customers/houselease/houselease_search.html", {**filter_args, "houselease_customers": houselease_customers})


def houselease_customer_delete(request, pk):
    houselease_customer = models.HouseLeaseCustomer.objects.filter(pk=pk).delete()
    return redirect(reverse("customers:house-lease-customer-list"))

"""below shoplease"""


class ShopLeaseCustomerList(ListView):
    model = models.ShopLeaseCustomer
    context_object_name = 'shoplease_customers'
    template_name = 'customers/shoplease/shoplease_list.html'


class ShopLeaseCustomerDeatil(DetailView):
    model = models.ShopLeaseCustomer
    template_name = 'customers/shoplease/shoplease_detail.html'


class ShopLeaseCustomerCreating(CreateView):
    form_class = forms.ShopLeaseCustomerForm
    template_name = 'customers/shoplease/shoplease_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:shop-lease-customer-list"))


class ShopLeaseCustomerUpdate(UpdateView):
    model = models.ShopLeaseCustomer
    template_name = "customers/shoplease/shoplease_update.html"
    fields = (
        "guest_phone",
        "updated",
        "deposit",
        "month_fee",
        "area_m2",
        "parking",
        "elevator",
        "finished",
        "description",
    )

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:shop-lease-customer-list"))


def shoplease_customer_search(request):

    deposit = int(request.GET.get("deposit", 0))
    month_fee = int(request.GET.get("month_fee", 0))
    area_m2 = int(request.GET.get("area_m2", 0))
    parking = request.GET.get("parking")
    elevator = request.GET.get("elevator")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
   
    filter_args = {}
    filter_args["deposit__lte"] = deposit
    filter_args["month_fee__lte"] = month_fee
    filter_args["area_m2__gte"] = area_m2
    if parking == "on":
        filter_args["parking"] = True
    if elevator == "on":
        filter_args["elevator"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    shoplease_customers = models.ShopLeaseCustomer.objects.filter(**filter_args)
    return render(request, "customers/shoplease/shoplease_search.html", {**filter_args, "shoplease_customers": shoplease_customers})


def shoplease_customer_delete(request, pk):
    shoplease_customer = models.ShopLeaseCustomer.objects.filter(pk=pk).delete()
    return redirect(reverse("customers:shop-lease-customer-list"))


"""below housedealing"""

class HouseDealingCustomerList(ListView):
    model = models.HouseDealingCustomer
    context_object_name = 'housedealing_customers'
    template_name = 'customers/housedealing/housedealing_list.html'


class HouseDealingCustomerDeatil(DetailView):
    model = models.HouseDealingCustomer
    template_name = 'customers/housedealing/housedealing_detail.html'


class HouseDealingCustomerCreating(CreateView):
    form_class = forms.HouseDealingCustomerForm
    template_name = 'customers/housedealing/housedealing_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:house-dealing-customer-list"))


class HouseDealingCustomerUpdate(UpdateView):
    model = models.HouseDealingCustomer
    template_name = "customers/housedealing/housedealing_update.html"
    fields = (
        "guest_phone",
        "price",
        "room",
        "area_m2",
        "parking",
        "elevator",
        "description",
        "not_finished",
        "finished",
    )

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:house-dealing-customer-list"))


def housedealing_customer_search(request):

    deposit = int(request.GET.get("deposit", 0))
    price = int(request.GET.get("price", 0))
    room = request.GET.get("room", 0)
    area_m2 = int(request.GET.get("area_m2", 0))
    parking = request.GET.get("parking")
    elevator = request.GET.get("elevator")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
   
    filter_args = {}
    filter_args["price__lte"] = price
    filter_args["area_m2__gte"] = area_m2
    filter_args["room__contains"] = room
    if parking == "on":
        filter_args["parking"] = True
    if elevator == "on":
        filter_args["elevator"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    housedealing_customers = models.HouseDealingCustomer.objects.filter(**filter_args)
    return render(request, "customers/housedealing/housedealing_search.html", {**filter_args, "housedealing_customers": housedealing_customers})


def housedealing_customer_delete(request, pk):
    housedealing_customer = models.HouseDealingCustomer.objects.filter(pk=pk).delete()
    return redirect(reverse("customers:house-dealing-customer-list"))


"""below buildingdealing"""

class BuildingDealingCustomerList(ListView):
    model = models.BuildingDealingCustomer
    context_object_name = 'buildingdealing_customers'
    template_name = 'customers/buildingdealing/buildingdealing_list.html'


class BuildingDealingCustomerDeatil(DetailView):
    model = models.BuildingDealingCustomer
    template_name = 'customers/buildingdealing/buildingdealing_detail.html'


class BuildingDealingCustomerCreating(CreateView):
    form_class = forms.BuildingDealingCustomerForm
    template_name = 'customers/buildingdealing/buildingdealing_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:building-dealing-customer-list"))


class BuildingDealingCustomerUpdate(UpdateView):
    model = models.BuildingDealingCustomer
    template_name = "customers/buildingdealing/buildingdealing_update.html"
    fields = (
        "guest_phone",
        "price",
        "elevator",
        "description",
        "not_finished",
        "finished",
    )

    def form_valid(self, form):
        form.save()
        return redirect(reverse("customers:building-dealing-customer-list"))


def buildingdealing_customer_search(request):

    price = int(request.GET.get("price", 0))
    elevator = request.GET.get("elevator")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
   
    filter_args = {}
    filter_args["price__lte"] = price
    if elevator == "on":
        filter_args["elevator"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    buildingdealing_customers = models.BuildingDealingCustomer.objects.filter(**filter_args)
    return render(request, "customers/buildingdealing/buildingdealing_search.html", {**filter_args, "buildingdealing_customers": buildingdealing_customers})


def buildingdealing_customer_delete(request, pk):
    buildingdealing_customer = models.BuildingDealingCustomer.objects.filter(pk=pk).delete()
    return redirect(reverse("customers:building-dealing-customer-list"))

templates/customers/buildingdealing/buildingdealing_creating.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
<button>손님 등록</button>
</form>
{% endblock content %}

templates/customers/buildingdealing/buildingdealing_detail.html
{% extends 'base.html' %}
{% block content %}
{% include "books/books_nav.html" %}
    <div>손님전화: {{object.guest_phone}}</div>
    <div>확인: {{object.updated|date:"SHORT_DATE_FORMAT"}}</div>
    <div>매매가: {{object.price}}만원</div>
    <div>E.V.: {{object.elevator}}</div>
    <div>비고: {{object.description}}</div>

    <a href="{% url 'customers:building-dealing-customer-update' object.pk %}">손님 정보 수정</a>
{% endblock content %}

templates/customers/buildingdealing/buildingdealing_list.html
{% extends 'base.html' %}
{% block content %}
<h5>Search</h5>
<form method="get" action="{% url 'customers:building-dealing-customer-search' %}">
    <label for='price'>매매가:</label><input value=0 type='number' id='price' name='price' />
    <label for='elevator'>E.V.:</label><input type='checkbox' id='elevator' name='elevator' />
    <label for='not_finished'>현재손님:</label><input checked type='checkbox' id='not_finished' name='not_finished' />
    <label for='finished'>완료손님:</label><input type='checkbox' id='finished' name='finished' />
    <button>Search</button>
</form>
<a href="{% url 'customers:building-dealing-customer-creating' %}">새 손님 등록</a>

<table style="width:100%">
    <tr>
        <th>No.</th>
        <th>손님전화</th>
        <th>확인일</th>
        <th>매매가</th>
        <th>E.V.</th>
        <th>현재손님</th>
        <th>완료손님</th>
        <th>비고</th>
        <th>손님관리</th>
    </tr>
    {% for list in buildingdealing_customers %}
    {% if user.pk == list.realtor.pk %}
    <tr>
        <th>{{forloop.counter}}</th>
        <th>{{list.guest_phone}}</th>
        <th>{{list.updated|date:"SHORT_DATE_FORMAT"}}</th>
        <th>{{list.price}}</th>
        <th>{{list.elevator}}</th>
        <th>{{list.not_finished}}</th>
        <th>{{list.finished}}</th>
        <th>{{list.description}}</th>
        <th>
            <div>
                <a href="{% url 'customers:building-dealing-customer-detail' list.pk %}">정보수정</a>
            </div>
            <!-- <div>
                <a href="{% url 'customers:building-dealing-customer-delete' list.pk %}">삭제</a>
            </div> -->
        </th>
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% endblock content %}

templates/customers/buildingdealing/buildingdealing_search.html
{% extends 'base.html' %}
{% block content %}
<form method="get" action="{% url 'customers:building-dealing-customer-search' %}">
    <label for='price'>매매가:</label><input value="{{price__lte}}" type='number' id='price' name='price' />
    <label for='elevator'>E.V.:</label><input {% if elevator %}checked{% endif %} type='checkbox' id='elevator' name='elevator' />
    <label for='not_finished'>현재손님:</label><input {% if not_finished %}checked{% endif %} type='checkbox' id='not_finished' name='not_finished' />
    <label for='finished'>완료손님:</label><input {% if finished %}checked{% endif %} type='checkbox' id='finished' name='finished' />
    <button>Search</button>
</form>

<table style="width:100%">
    <tr>
        <th>No.</th>
        <th>손님 전화</th>
        <th>확인</th>
        <th>매매가</th>
        <th>E.V.</th>
        <th>현재손님</th>
        <th>완료손님</th>
        <th>비고</th>
        <th>손님관리</th>
    </tr>
    {% for list in buildingdealing_customers %}
    {% if user.pk == list.realtor.pk %}
    <tr>
        <th>{{forloop.counter}}</th>
        <th>{{list.guest_phone}}</th>
        <th>{{list.updated|date:"SHORT_DATE_FORMAT"}}</th>
        <th>{{list.price}}</th>
        <th>{{list.elevator}}</th>
        <th>{{list.not_finished}}</th>
        <th>{{list.finished}}</th>
        <th>{{list.description}}</th>
        <th>
            <div>
                <a href="{% url 'customers:building-dealing-customer-detail' list.pk %}">정보수정</a>
            </div>
            <!-- <div>
                <a href="{% url 'customers:building-dealing-customer-delete' list.pk %}">삭제</a>
            </div> -->
        </th>
    </tr>
    {% endif %}
    {% endfor %}
</table>

{% endblock content %}

templates/customers/buildingdealing/buildingdealing_update.html
roomlease_update.html
{% include "books/books_nav.html" %}

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>수정 완료</button>
</form>