books/urls.py
from django.urls import path
from books.views import RoomLeaseList, RoomDealingList, RoomLeaseCreating, RoomLeaseDeatil, RoomLeaseUpdate, roomlease_search, roomlease_delete, StoreLeaseList, StoreLeaseDeatil, StoreLeaseCreating, StoreLeaseUpdate, storelease_search, storelease_delete, RoomDealingDeatil, RoomDealingUpdate, roomdealing_delete, roomdealing_search, RoomDealingCreating, BuildingDealingList, BuildingDealingDeatil, BuildingDealingUpdate, buildingdealing_delete, buildingdealing_search, BuildingDealingCreating

app_name = 'books'

urlpatterns = [
    path("room-lease/", RoomLeaseList.as_view(), name="room-lease-list"),
    path("room-lease/<int:pk>/", RoomLeaseDeatil.as_view(),
         name="room-lease-detail"),
    path("room-lease/<int:pk>/update/",
         RoomLeaseUpdate.as_view(), name="room-lease-update"),
    path("room-lease/<int:pk>/delete/",
         roomlease_delete, name="room-lease-delete"),
    path("room-lease/search/", roomlease_search, name="room-lease-search"),
    path("room-lease/creating/", RoomLeaseCreating.as_view(),
         name="room-lease-creating"),
    path("room-dealing/", RoomDealingList.as_view(), name="room-dealing-list"),
    path("room-dealing/<int:pk>/", RoomDealingDeatil.as_view(),
         name="room-dealing-detail"),
    path("room-dealing/<int:pk>/update/",
         RoomDealingUpdate.as_view(), name="room-dealing-update"),
    path("room-dealing/<int:pk>/delete/",
         roomdealing_delete, name="room-dealing-delete"),
    path("room-dealing/search/", roomdealing_search, name="room-dealing-search"),
    path("room-dealing/creating/", RoomDealingCreating.as_view(),
         name="room-dealing-creating"),
    path("store-lease/", StoreLeaseList.as_view(), name="store-lease-list"),
    path("store-lease/<int:pk>/", StoreLeaseDeatil.as_view(),
         name="store-lease-detail"),
    path("store-lease/creating/", StoreLeaseCreating.as_view(),
         name="store-lease-creating"),
    path("store-lease/<int:pk>/update/",
         StoreLeaseUpdate.as_view(), name="store-lease-update"),
    path("store-lease/search/", storelease_search, name="store-lease-search"),
    path("store-lease/<int:pk>/delete/",
         storelease_delete, name="store-lease-delete"),
    path("building-dealing/", BuildingDealingList.as_view(),
         name="building-dealing-list"),
    path("building-dealing/<int:pk>/", BuildingDealingDeatil.as_view(),
         name="building-dealing-detail"),
    path("building-dealing/<int:pk>/update/",
         BuildingDealingUpdate.as_view(), name="building-dealing-update"),
    path("building-dealing/<int:pk>/delete/",
         buildingdealing_delete, name="building-dealing-delete"),
    path("building-dealing/search/", buildingdealing_search,
         name="building-dealing-search"),
    path("building-dealing/creating/", BuildingDealingCreating.as_view(),
         name="building-dealing-creating"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("contracts/", include('contracts.urls', namespace='contracts')),
    path("users/", include('users.urls', namespace='users')),
    path("books/", include('books.urls', namespace='books')),
    path("customers/", include('customers.urls', namespace='customers')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from homes import views as home_views

app_name = "core"

urlpatterns = [
    path("", home_views.homes, name='home'),
]

books/forms.py
from django import forms
from . import models


class RoomLeaseForm(forms.ModelForm):
    class Meta:
        model = models.RoomLease
        """fields = (
            'realtor',
            'address',
            "deposit",
            "month_fee",
            "management_fee",
            "area_m2",
            "room",
            "bath",
            "owner_phone",
            "tenant_phone",
            "parking",
            "elevator",
            "loan",
            "empty",
            "naver",
            "not_finished",
            "finished",
            "description")"""
        """"fields = '__all__'"""
        exclude = ['realtor']


class RoomDealingForm(forms.ModelForm):
    class Meta:
        model = models.RoomDealing
        fields = ('address',
                  'price',
                  "deposit",
                  "month_fee",
                  "management_fee",
                  "area_m2",
                  "room",
                  "bath",
                  "owner_phone",
                  "tenant_phone",
                  "parking",
                  "elevator",
                  "empty",
                  "naver",
                  "not_finished",
                  "finished",
                  "description")


class StoreLeaseForm(forms.ModelForm):
    class Meta:
        model = models.StoreLease
        fields = ('address',
                  'right_deposit',
                  "deposit",
                  "month_fee",
                  "management_fee",
                  "area_m2",
                  "owner_phone",
                  "tenant_phone",
                  "parking",
                  "elevator",
                  "empty",
                  "naver",
                  "not_finished",
                  "finished",
                  "description")


class BuildingDealingForm(forms.ModelForm):
    class Meta:
        model = models.BuildingDealing
        fields = ('address',
                  'price',
                  'equity',
                  "deposit",
                  "month_fee",
                  "land_m2",
                  'land_type',
                  "owner_phone",
                  "elevator",
                  "naver",
                  "not_finished",
                  "finished",
                  "description")

books/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from . import models, forms
from books import models as models_users


class RoomLeaseList(ListView):
    model = models.RoomLease
    context_object_name = 'roomlease'
    template_name = 'books/roomlease/roomlease_list.html'


class RoomLeaseDeatil(DetailView):
    model = models.RoomLease
    template_name = 'books/roomlease/roomlease_detail.html'


class RoomLeaseCreating(CreateView):
    form_class = forms.RoomLeaseForm
    template_name = 'books/roomlease/roomlease_creating.html'

    def form_valid(self, form):
        book = form.save()
        book.realtor = self.request.user                    
        book.save()
        return redirect(reverse("books:room-lease-list"))

    # def get_success_url(self):
    #     return reverse("books:room-lease-list")   # 위 아래 둘 다 가능


class RoomLeaseUpdate(UpdateView):
    model = models.RoomLease
    template_name = "books/roomlease/roomlease_update.html"
    fields = ('address',
              "deposit",
              "month_fee",
              "area_m2",
              "room",
              "bath",
              "owner_phone",
              "tenant_phone",
              "parking",
              "elevator",
              "loan",
              "empty",
              "naver",
              "not_finished",
              "finished",
              "description")

    def form_valid(self, form):
        form.save()
        return redirect(reverse("books:room-lease-list"))


def roomlease_search(request):

    address = request.GET.get("address")
    deposit = int(request.GET.get("deposit", 0))
    month_fee = int(request.GET.get("month_fee", 0))
    area_m2 = int(request.GET.get("area_m2", 0))
    room = request.GET.get("room", 0)
    parking = request.GET.get("parking")
    elevator = request.GET.get("elevator")
    loan = request.GET.get("loan")
    empty = request.GET.get("empty")
    naver = request.GET.get("naver")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
    description = request.GET.get("description")

    filter_args = {}
    filter_args["address__contains"] = address
    filter_args["deposit__lte"] = deposit
    filter_args["month_fee__lte"] = month_fee
    filter_args["area_m2__gte"] = area_m2
    filter_args["room__contains"] = room
    if parking == "on":
        filter_args["parking"] = True
    if elevator == "on":
        filter_args["elevator"] = True
    if loan == "on":
        filter_args["loan"] = True
    if empty == "on":
        filter_args["empty"] = True
    if naver == "on":
        filter_args["naver"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    lease = models.RoomLease.objects.filter(**filter_args)
    return render(request, "books/roomlease/roomlease_search.html", {**filter_args, "lease": lease})


def roomlease_delete(request, pk):
    room = models.RoomLease.objects.filter(pk=pk).delete()
    return redirect(reverse("books:room-lease-list"))


"""below house dealing"""


class RoomDealingList(ListView):
    model = models.RoomDealing
    context_object_name = 'roomdealing'
    template_name = 'books/roomdealing/roomdealing_list.html'


class RoomDealingDeatil(DetailView):
    model = models.RoomDealing
    template_name = 'books/roomdealing/roomdealing_detail.html'


class RoomDealingCreating(CreateView):
    form_class = forms.RoomDealingForm
    template_name = 'books/roomdealing/roomdealing_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("books:room-dealing-list"))


class RoomDealingUpdate(UpdateView):
    model = models.RoomDealing
    template_name = "books/roomdealing/roomdealing_update.html"
    fields = ('address',
              'price',
              "deposit",
              "month_fee",
              "area_m2",
              "room",
              "bath",
              "owner_phone",
              "tenant_phone",
              "parking",
              "elevator",
              "loan",
              "empty",
              "naver",
              "not_finished",
              "finished",
              "description")

    def form_valid(self, form):
        form.save()
        return redirect(reverse("books:room-dealing-list"))


def roomdealing_search(request):

    address = request.GET.get("address")
    price = int(request.GET.get("price", 0))
    deposit = int(request.GET.get("deposit", 0))
    month_fee = int(request.GET.get("month_fee", 0))
    area_m2 = int(request.GET.get("area_m2", 0))
    room = request.GET.get("room", 0)
    parking = request.GET.get("parking")
    elevator = request.GET.get("elevator")
    loan = request.GET.get("loan")
    empty = request.GET.get("empty")
    naver = request.GET.get("naver")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
    description = request.GET.get("description")

    filter_args = {}
    filter_args["address__contains"] = address
    filter_args["price__lte"] = price
    filter_args["deposit__lte"] = deposit
    filter_args["month_fee__lte"] = month_fee
    filter_args["area_m2__gte"] = area_m2
    filter_args["room__contains"] = room
    if parking == "on":
        filter_args["parking"] = True
    if elevator == "on":
        filter_args["elevator"] = True
    if loan == "on":
        filter_args["loan"] = True
    if empty == "on":
        filter_args["empty"] = True
    if naver == "on":
        filter_args["naver"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    lease = models.RoomDealing.objects.filter(**filter_args)
    return render(request, "books/roomdealing/roomdealing_search.html", {**filter_args, "lease": lease})


def roomdealing_delete(request, pk):
    room = models.RoomDealing.objects.filter(pk=pk).delete()
    return redirect(reverse("books:room-dealing-list"))


"""below store"""


class StoreLeaseList(ListView):
    model = models.StoreLease
    context_object_name = 'storelease'
    template_name = 'books/storelease/storelease_list.html'


class StoreLeaseDeatil(DetailView):
    model = models.StoreLease
    template_name = 'books/storelease/storelease_detail.html'


class StoreLeaseCreating(CreateView):
    form_class = forms.StoreLeaseForm
    template_name = 'books/storelease/storelease_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("books:store-lease-list"))

    # def get_success_url(self):
    #     return reverse("books:room-lease-list")   # 위 아래 둘 다 가능


class StoreLeaseUpdate(UpdateView):
    model = models.RoomLease
    template_name = "books/storelease/storelease_update.html"
    fields = ('address',
              "right_deposit",
              "deposit",
              "month_fee",
              "management_fee",
              "area_m2",
              "owner_phone",
              "tenant_phone",
              "parking",
              "elevator",
              "empty",
              "naver",
              "not_finished",
              "finished",
              "description")

    def form_valid(self, form):
        form.save()
        return redirect(reverse("books:store-lease-list"))


def storelease_search(request):

    address = request.GET.get("address")
    right_deposit = int(request.GET.get("right_deposit", 0))
    deposit = int(request.GET.get("deposit", 0))
    month_fee = int(request.GET.get("month_fee", 0))
    area_m2 = int(request.GET.get("area_m2", 0))
    parking = request.GET.get("parking")
    elevator = request.GET.get("elevator")
    empty = request.GET.get("empty")
    naver = request.GET.get("naver")
    not_finished = request.GET.get("not_finished")
    finished = request.GET.get("finished")
    description = request.GET.get("description")

    filter_args = {}
    filter_args["address__contains"] = address
    filter_args["right_deposit__lte"] = right_deposit
    filter_args["deposit__lte"] = deposit
    filter_args["month_fee__lte"] = month_fee
    filter_args["area_m2__gte"] = area_m2
    if parking == "on":
        filter_args["parking"] = True
    if elevator == "on":
        filter_args["elevator"] = True
    if empty == "on":
        filter_args["empty"] = True
    if naver == "on":
        filter_args["naver"] = True
    if not_finished == "on":
        filter_args["not_finished"] = True
    if finished == "on":
        filter_args["finished"] = True
    lease = models.StoreLease.objects.filter(**filter_args)
    return render(request, "books/storelease/storelease_search.html", {**filter_args, "lease": lease})


def storelease_delete(request, pk):
    room = models.StoreLease.objects.filter(pk=pk).delete()
    return redirect(reverse("books:store-lease-list"))


"""below building"""


class BuildingDealingList(ListView):
    model = models.BuildingDealing
    context_object_name = 'buildingdealing'
    template_name = 'books/buildingdealing/buildingdealing_list.html'


class BuildingDealingDeatil(DetailView):
    model = models.BuildingDealing
    template_name = 'books/buildingdealing/buildingdealing_detail.html'


class BuildingDealingCreating(CreateView):
    form_class = forms.BuildingDealingForm
    template_name = 'books/buildingdealing/buildingdealing_creating.html'

    def form_valid(self, form):
        form.save()
        return redirect(reverse("books:building-dealing-list"))


class BuildingDealingUpdate(UpdateView):
    model = models.BuildingDealing
    template_name = "books/buildingdealing/buildingdealing_update.html"
    fields = ('address',
              'price',
              'equity',
              "deposit",
              "month_fee",
              "land_m2",
              'land_type',
              "owner_phone",
              "elevator",
              "empty",

templates/books/storelease/storelease_creating.html
{% extends 'base.html' %}
{% block content %}
storelease_creating.html
{% include "books/books_nav.html" %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
<button>매물 등록</button>
</form>
{% endblock content %}

templates/books/storelease/storelease_detail.html
{% extends 'base.html' %}
{% block content %}
{% include "books/books_nav.html" %}
    <div>주소: {{object.address}}</div>
    <div>권리금: {{object.right_deposit}}만원</div>
    <div>보증금: {{object.deposit}}만원</div>
    <div>월세: {{object.mondiv_fee}}만원</div>
    <div>관리비: {{object.management_fee}}만원</div>
    <div>면적: {{object.area_m2}}m2</div>
    <div>집주인: {{object.owner_phone}}</div>
    <div>세입자: {{object.tenant_phone}}</div>
    <div>주차: {{object.parking}}</div>
    <div>E.V.: {{object.elevator}}</div>
    <div>공실: {{object.empty}}</div>
    <div>Naver: {{object.naver}}</div>
    <div>현재매물: {{object.not_finished}}</div>
    <div>완료매물: {{object.finished}}</div>
    <div>비고: {{object.description}}</div>

    <a href="{% url 'books:store-lease-update' object.pk %}">매물 정보 수정</a>
{% endblock content %}

templates/books/storelease/storelease_list.html
{% extends 'base.html' %}
{% block content %}
<h5>Search</h5>
{% include "books/books_nav.html" %}
<form method="get" action="{% url 'books:store-lease-search' %}">
    <label for='address'>주소:</label><input id='address' name='address' />
    <label for="right_deposit">권리금:</label><input value=0 type="number" id="right_deposit" name="right_deposit" />
    <label for='deposit'>보증금:</label><input value=0 type='number' id='deposit' name='deposit' />
    <label for='month_fee'>월세:</label><input value=0 type='number' id='month_fee' name='month_fee' />
    <label for='area_m2'>면적:</label><input value=0 type='number' id='area_m2' name='area_m2' />   
    <label for='parking'>주차:</label><input type='checkbox' id='parking' name='parking' />
    <label for='elevator'>E.V.:</label><input type='checkbox' id='elevator' name='elevator' />
    <label for='empty'>공실:</label><input type='checkbox' id='empty' name='empty' />
    <label for='naver'>Naver:</label><input type='checkbox' id='naver' name='naver' />
    <label for='not_finished'>현재매물:</label><input checked type='checkbox' id='not_finished' name='not_finished' />
    <label for='finished'>완료매물:</label><input type='checkbox' id='finished' name='finished' />
    <button>Search</button>
</form>
<a href="{% url 'books:store-lease-creating' %}">새 매물 등록</a>

<table style="width:100%">
    <tr>
        <th>No.</th>
        <th>주소</th>
        <th>확인일</th>
        <th>권리금</th>
        <th>보증금</th>
        <th>월세</th>
        <th>면적m2</th>
        <th>집주인</th>
        <th>세입자</th>
        <th>주차</th>
        <th>E.V.</th>
        <th>공실</th>
        <th>Naver</th>
        <th>현재매물</th>
        <th>완료매물</th>
        <th>비고</th>
        <th>매물관리</th>
    </tr>
    {% for list in storelease %}
    {% if user.pk == list.realtor.pk %}
    <tr>
        <th>{{forloop.counter}}</th>
        <th>{{list.address}}</a></th>
        <th>{{list.updated}}</th>
        <th>{{list.right_deposit}}</th>
        <th>{{list.deposit}}</th>
        <th>{{list.month_fee}}</th>
        <th>{{list.area_m2}}</th>
        <th>{{list.owner_phone}}</th>
        <th>{{list.tenant_phone}}</th>
        <th>{{list.parking}}</th>
        <th>{{list.elevator}}</th>
        <th>{{list.empty}}</th>
        <th>{{list.naver}}</th>
        <th>{{list.not_finished}}</th>
        <th>{{list.finished}}</th>
        <th>{{list.description}}</th>
        <th>
            <div>
                <a href="{% url 'books:store-lease-detail' list.pk %}">정보수정</a>
            </div>
            <!-- <div>
                <a href="{% url 'books:store-lease-delete' list.pk %}">삭제</a>
            </div> -->
        </th>
    </tr>
    {% endif %}
    {% endfor %}
</table>
{% endblock content %}

templates/books/storelease/storelease_search.html
{% extends 'base.html' %}
{% block content %}
<h2>storelease_search.html</h2>
{% include "books/books_nav.html" %}
<form method="get" action="{% url 'books:store-lease-search' %}">
    <label for='address'>주소:</label><input value = "{{address__contains}}" id='address' name='address' />
    <label for='right_deposit'>권리금:</label><input value="{{right_deposit__lte}}" type='number' id='right_deposit' name='right_deposit' />
    <label for='deposit'>보증금:</label><input value="{{deposit__lte}}" type='number' id='deposit' name='deposit' />
    <label for='month_fee'>월세:</label><input value="{{month_fee__lte}}"" type='number' id='month_fee' name='month_fee' />
    <label for='area_m2'>면적:</label><input value="{{area_m2__gte}}" type='number' id='area_m2' name='area_m2' />   
    <label for='parking'>주차:</label><input {% if parking %}checked{% endif %} type='checkbox' id='parking' name='parking' />
    <label for='elevator'>E.V.:</label><input {% if elevator %}checked{% endif %} type='checkbox' id='elevator' name='elevator' />
    <label for='empty'>공실:</label><input {% if empty %}checked{% endif %} type='checkbox' id='empty' name='empty' />
    <label for='naver'>Naver:</label><input {% if naver %}checked{% endif %} type='checkbox' id='naver' name='naver' />
    <label for='not_finished'>현재매물:</label><input {% if not_finished %}checked{% endif %} type='checkbox' id='not_finished' name='not_finished' />
    <label for='finished'>완료매물:</label><input {% if finished %}checked{% endif %} type='checkbox' id='finished' name='finished' />
    <button>Search</button>
</form>

<table style="width:100%">
    <tr>
        <th>No.</th>
        <th>주소</th>
        <th>권리금</th>
        <th>보증금</th>
        <th>월세</th>
        <th>면적m2</th>
        <th>주차</th>
        <th>E.V.</th>
        <th>공실</th>
        <th>집주인</th>
        <th>세입자</th>
        <th>Naver</th>
        <th>비고</th>
        <th>매물관리</th>
    </tr>
    {% for list in lease %}
    {% if user.pk == list.realtor.pk %}
    <tr>
        <th>{{forloop.counter}}</th>
        <th>{{list.address}}</th>
        <th>{{list.right_deposit}}</th>
        <th>{{list.deposit}}</th>
        <th>{{list.month_fee}}</th>
        <th>{{list.area_m2}}</th>
        <th>{{list.parking}}</th>
        <th>{{list.elevator}}</th>
        <th>{{list.empty}}</th>
        <th>{{list.owner_phone}}</th>
        <th>{{list.tenant_phone}}</th>
        <th>{{list.naver}}</th>
        <th>{{list.description}}</th>
        <th>
            <div>
                <a href="{% url 'books:store-lease-detail' list.pk %}">정보수정</a>
            </div>
            <!-- <div>
                <a href="{% url 'books:store-lease-delete' list.pk %}">삭제</a>
            </div> -->
        </th>
    </tr>
    {% endif %}
    {% endfor %}
</table>

{% endblock content %}

templates/books/storelease/storelease_update.html
roomlease_update.html
{% include "books/books_nav.html" %}

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>수정 완료</button>
</form>